# Generated by Django 3.1.1 on 2020-09-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upvote',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='view',
            field=models.SmallIntegerField(null=True),
        ),
    ]
