# Generated by Django 3.1.1 on 2020-09-15 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0003_auto_20200915_2349'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Posted')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='Blog.post')),
                ('commentator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
